In [16]:
import numpy as np
from math import isclose

#横向输入 
A = np.array([[1,2],[3,4]])
B = np.array([4, 10])
#x+2y=4
#3x+4y=10
x = np.linalg.solve(A,B)
x[1]

1.0000000000000002

In [17]:
y=1.999999999
isclose(y, round(y))

True

In [18]:
a=1153
b=str(a)
b

'1153'

In [23]:
#点亮相同数量
#3个

s=np.array([1,2,3])

A=np.array([[1,1,0],[1,1,1],[0,1,1]])

n=0
for i in range(1,999):
    t=str(i)
    steps=np.zeros(3)
    for j in range(len(t)):
        steps[j]=int(t[j])
    x=np.mod(s+np.matmul(A,steps),np.array([3,3,3]))
    if round(x[0])==round(x[1])==round(x[2]):
        if(steps.sum()<=3):
            print(steps)
            n=n+1
        if(n==20):
            break


[1. 0. 2.]


In [20]:
#4个

s=np.array([1,2,3,1])

A=np.array([[1,1,0,0],[1,1,1,0],[0,1,1,1],[0,0,1,1]])

n=0
for i in range(1,9999):
    t=str(i)
    steps=np.zeros(4)
    for j in range(len(t)):
        steps[j]=int(t[j])
    x=np.mod(s+np.matmul(A,steps),np.array([3,3,3,3]))
    if round(x[0])==round(x[1])==round(x[2])==round(x[3]):
        if(steps.sum()<=8):
            print(steps)
            n=n+1
        if(n==20):
            break

[1. 1. 2. 0.]
[1. 1. 5. 0.]
[1. 4. 2. 0.]
[4. 1. 2. 0.]
[1. 1. 2. 0.]
[1. 1. 2. 3.]
[1. 1. 5. 0.]
[1. 4. 2. 0.]
[2. 1. 2. 1.]
[3. 1. 2. 2.]
[4. 1. 2. 0.]


In [15]:
#5个

s=np.array([2,1,2,1,2])

A=np.array([[1,1,0,0,0],[1,1,1,0,0],[0,1,1,1,0]
,[0,0,1,1,1],[0,0,0,1,1]])

n=0
for i in range(1,99999):
    t=str(i)
    steps=np.zeros(5)
    for j in range(len(t)):
        steps[j]=int(t[j])
    x=np.mod(s+np.matmul(A,steps),np.array([3,3,3,3,3]))
    if round(x[0])==round(x[1])==round(x[2])==round(x[3])==round(x[4]):
        if(steps.sum()<=5):
            print(steps)
            n=n+1
        if(n==20):
            break

[1. 2. 1. 0. 0.]
[1. 2. 1. 0. 0.]
[1. 0. 1. 0. 1.]
[1. 1. 1. 0. 2.]
[1. 2. 1. 0. 0.]
[2. 0. 1. 1. 1.]


In [21]:
#旋转类
#5个，朝向，四为周期，逆时针+1

s=np.array([2,2,2,3,3])

A=np.array([[1,1,0,0,0],[1,1,1,0,0],[1,1,1,1,1]
,[0,0,1,1,1],[0,0,0,1,1]])

n=0
for i in range(1,99999):
    t=str(i)
    steps=np.zeros(5)
    for j in range(len(t)):
        steps[j]=int(t[j])
    x=np.mod(s+np.matmul(A,steps),np.array([4,4,4,4,4]))
    if round(x[0])==round(x[1])==round(x[2])==round(x[3])==round(x[4]):
        if(steps.sum()<=3):
            print(steps)
            n=n+1
        if(n==20):
            break

[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]


In [22]:
#情况太多了，不写了QAQ

In [6]:
sum=0
for i in range(16,20):
    print(round(1/i,3))
    sum=sum+round(1/i,3)
print(sum)

0.062
0.059
0.056
0.053
0.22999999999999998
