In [15]:
import numpy as np
a = np.array([[2, 2, 1],[1, 3, 1], [1, 2, 2]])
print("a = ")
print(a)#面积,可以看是否映射到一点，一线
det = np.linalg.det(a)
print("\nDeterminant:", np.round(det))

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Determinant: 5.0


$$\text{det}\begin{pmatrix}
  a& b\\
  c&d
\end{pmatrix}=\begin{vmatrix}
 a &b \\
c  &d
\end{vmatrix}=ad-bc$$

$$ \begin{cases}    { 3 x - 2 y = 1 } \\ { - x + 4 y = 3 } \end{cases}$$

In [16]:
M=np.array([[3,-2],[-1,4]])
N=np.linalg.inv(M)
N

array([[0.4, 0.2],
       [0.1, 0.3]])

In [17]:
res=np.dot(N,np.array([1,3]))
res

array([1., 1.])

In [20]:
a=np.array([[8,-5],[6,-3]])
print("a = ")
print(a)
w, v = np.linalg.eig(a)
print("\nEigenvalues:")
print(w)
print("\nEigenvectors:")
print(v)

a = 
[[ 8 -5]
 [ 6 -3]]

Eigenvalues:
[3. 2.]

Eigenvectors:
[[0.70710678 0.6401844 ]
 [0.70710678 0.76822128]]
